In [1]:
import numpy as np
import pandas as pd

In [3]:
x = np.linspace(1, 10, 5)
x

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [6]:
x.reshape(-1,1)

array([[ 1.  ],
       [ 3.25],
       [ 5.5 ],
       [ 7.75],
       [10.  ]])

In [10]:
x.T

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [11]:
1e5

100000.0