In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.datasets import load_diabetes

In [3]:
X, y = load_diabetes(return_X_y = True)

In [4]:
X.shape

(442, 10)

In [5]:
y.shape

(442,)

In [6]:
from sklearn.model_selection import train_test_split as tts
from sklearn.linear_model import LinearRegression

In [7]:
X_train, X_test, y_train, y_test = tts(X, y, test_size = 0.3, random_state = 80)


In [8]:
X_train.shape

(309, 10)

In [9]:
X_test.shape

(133, 10)

In [10]:
y_train.shape

(309,)

In [11]:
y_test.shape

(133,)

In [12]:
model = LinearRegression()

In [13]:
model.fit(X_train, y_train)

LinearRegression()

In [14]:
model.coef_

array([ -45.84494218, -221.74694279,  539.0744349 ,  363.33904261,
       -825.080232  ,  515.00340371,   99.51926158,  170.20876912,
        727.7570423 ,   80.55454898])

In [15]:
model.intercept_

151.40878574303605

In [16]:
from sklearn.metrics import r2_score

In [17]:
score = r2_score(y_test, model.predict(X_test))
score

0.5197238863575131

# Implementing Batch Gradient Descent

In [18]:
class BatchGDRegressor:
    def __init__(self, learning_rate = 0.01, epochs = 100):
        self.coef_ = None
        self.intercept_ = None
        self.epochs = epochs
        self.lr = learning_rate

    def fit(self, X_train # n0 * m
            , y_train # n0 * 1
           ):
        # calculate the values for all the coefs 
        self.coef_ = np.ones(X_train.shape[1]) # (m * 1)
        self.intercept_ = 0

        for _ in range(self.epochs):
            # update the values of self.intercept_
            y_pred = self.intercept_ + X_train @ self.coef_ # (n0 * m) @ (m * 1) == (n0 * 1)

            # updating the intercept
            del_beta_not = (2 * np.sum(y_pred - y_train))/X_train.shape[0]
            self.intercept_ = self.intercept_ - self.lr * del_beta_not

            # updating the other coefficients
            others = 2 * ((y_pred - y_train) @ X_train) / X_train.shape[0] # (n0 * 1) @ (n0 * m) == (m * 1)

            self.coef_ = self.coef_ - self.lr * others

    def predict(self, X_test # n1 * m
               ):
        return X_test @ self.coef_ + self.intercept_

In [19]:
gdr = BatchGDRegressor(learning_rate = 0.5, epochs = 300000)

In [20]:
gdr.fit(X_train, y_train)

In [21]:
model.coef_

array([ -45.84494218, -221.74694279,  539.0744349 ,  363.33904261,
       -825.080232  ,  515.00340371,   99.51926158,  170.20876912,
        727.7570423 ,   80.55454898])

In [22]:
gdr.coef_

array([ -45.84328638, -221.7300273 ,  539.11688254,  363.32691685,
       -822.54736314,  512.98264269,   98.39848582,  169.89324426,
        726.80675492,   80.56512966])

In [23]:
gdr.intercept_

151.4088571901892

In [24]:
model.intercept_

151.40878574303605